"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]
prepend_keymap = [
  # Plugins
  # Smart Enter
  { on = "l", run = [
    "plugin --sync smart-enter",
  ], desc = "Enter the child directory, or open the file" },
  { on = "<Right>", run = [
    "plugin --sync smart-enter",
  ], desc = "Enter the child directory, or open the file" },
  # What Size
  { on = [
    ".",
    "s",
  ], run = "plugin what-size", desc = "Calc size of selection or cwd" },
  # Max-Preview
  { on = [
    "M",
  ], run = "plugin max-preview", desc = "Maximize or restore preview" },

  # Hopping
  { on = [
    "K",
  ], run = "arrow -5", desc = "Move cursor up 5 lines" },
  { on = [
    "J",
  ], run = "arrow 5", desc = "Move cursor down 5 lines" },
  { on = [
    "<S-Up>",
  ], run = "arrow -5", desc = "Move cursor up 5 lines" },
  { on = [
    "<S-Down>",
  ], run = "arrow 5", desc = "Move cursor down 5 lines" },

  # Seeking
  { on = [
    "<C-k>",
  ], run = "seek -5", desc = "Seek up 5 units in the preview" },
  { on = [
    "<C-j>",
  ], run = "seek 5", desc = "Seek down 5 units in the preview" },
  { on = [
    "<C-Up>",
  ], run = "seek -5", desc = "Seek up 5 units in the preview" },
  { on = [
    "<C-Down>",
  ], run = "seek 5", desc = "Seek down 5 units in the preview" },

  # Go To
  { on = [
    "g",
    ".",
  ], run = "cd ~/.dotfiles/", desc = "the dotfiles directory" },
  { on = [
    "g",
    "c",
  ], run = "cd ~/.config/", desc = "the config directory" },
  { on = [
    "g",
    "d",
  ], run = "cd ~/Downloads/", desc = "the downloads directory" },
  { on = [
    "g",
    "h",
  ], run = "cd ~", desc = "the home directory" },
  { on = [
    "g",
    "n",
  ], run = "cd ~/.config/nvim/", desc = "the neovim config directory" },
  { on = [
    "g",
    "t",
  ], run = "cd ~/.local/share/Trash/files/", desc = "the trash directory" },
  { on = [
    "g",
    "w",
  ], run = "cd ~/Dev/", desc = "the dev directory" },
  { on = [
    "g",
    "f",
  ], run = "cd ~/finance/", desc = "the finance directory" },

  # Toggle
  { on = [
    "<C-Space>",
  ], run = [
    "toggle",
    "arrow -1",
  ], desc = "Toggle the current selection state" },

  # Operation
  { on = [
    "R",
  ], run = "rename --empty=stem --cursor=start", desc = "Rename a file and wait to paste a copied value" },
  { on = [
    "<C-s>",
  ], run = 'shell "$SHELL" --block --confirm', desc = "Open shell here" },

]
