[mgr]
cwd = { fg = "#e8d5b7", italic = true }

# Hovered - warm earth tone highlight
hovered = { bg = "#352f24" }
preview_hovered = { bg = "#352f24" }

# Find - using MonaLisa gold tones
find_keyword = { fg = "#1e1c18", bg = "#e2b55f", bold = true }
find_position = { fg = "#7a8471", bg = "#2b271f", bold = true }

# Markers - artistic inspired colors
marker_copied = { fg = "#8a7c4a", bg = "#8a7c4a" }
marker_cut = { fg = "#c46f41", bg = "#c46f41" }
marker_marked = { fg = "#6d7a72", bg = "#6d7a72" }
marker_selected = { fg = "#b08080", bg = "#b08080" }

# Count - warm harmonious backgrounds
count_copied = { fg = "#e8d5b7", bg = "#5d5242" }
count_cut = { fg = "#e8d5b7", bg = "#4f4535" }
count_selected = { fg = "#e8d5b7", bg = "#423a2b" }

# Border - elegant earth tone
border_symbol = "│"
border_style = { fg = "#7d6f61" }

[tabs]
tab_active = { fg = "#e8d5b7", bg = "#352f24" }
tab_inactive = { fg = "#6b5d4f", bg = "#1e1c18" }

[mode]
normal_main = { fg = "#1e1c18", bg = "#b08080", bold = true }
normal_alt = { fg = "#b08080", bg = "#423a2b" }

select_main = { fg = "#1e1c18", bg = "#6d7a72", bold = true }
select_alt = { fg = "#6d7a72", bg = "#423a2b" }

unset_main = { fg = "#1e1c18", bg = "#e2b55f", bold = true }
unset_alt = { fg = "#e2b55f", bg = "#423a2b" }

[status]
separator_open = ""
separator_close = ""

# Progress - MonaLisa inspired
progress_label = { fg = "#7d6f61", bold = true }
progress_normal = { fg = "#1e1c18" }
progress_error = { fg = "#c46f41" }

# Permissions - artistic color coding
perm_type = { fg = "#b08080" }
perm_read = { fg = "#e2b55f" }
perm_write = { fg = "#c46f41" }
perm_exec = { fg = "#8a7c4a" }
perm_sep = { fg = "#5d5242" }

[pick]
border = { fg = "#7d6f61" }
active = { fg = "#e8d5b7", bg = "#4f4535" }
inactive = { fg = "#e8d5b7" }

[input]
border = { fg = "#7a8471" }
title = { fg = "#7a8471" }
value = { fg = "#e2b55f" }
selected = { bg = "#4f4535" }

[completion]
border = { fg = "#7a8471" }
active = { fg = "#e8d5b7", bg = "#4f4535" }
inactive = { fg = "#e8d5b7" }

icon_file = ""
icon_folder = ""
icon_command = ""

[tasks]
border = { fg = "#7d6f61" }
title = { fg = "#7d6f61" }
hovered = { fg = "#e8d5b7", bg = "#4f4535" }

[which]
cols = 3
mask = { bg = "#1e1c18" }
cand = { fg = "#7a8471" }
rest = { fg = "#b08080" }
desc = { fg = "#6d7a72" }
separator = " ➜ "
separator_style = { fg = "#8f8173" }

[confirm]
border = { fg = "#7a8471" }
title = { fg = "#7d6f61" }
content = {}
list = {}
btn_yes = { bg = "#4f4535" }
btn_no = {}
btn_labels = ["  [Y]es  ", "  (N)o  "]

[spot]
border = { fg = "#7d6f61" }
title = { fg = "#7d6f61" }

[notify]
title_info = { fg = "#7a8471" }
title_warn = { fg = "#e2b55f" }
title_error = { fg = "#c46f41" }

icon_error = ""
icon_warn = ""
icon_info = ""

[help]
on = { fg = "#8a7c4a" }
run = { fg = "#6d7a72" }
hovered = { bg = "#352f24" }
footer = { fg = "#e8d5b7", bg = "#1e1c18" }

[filetype]
rules = [
  # Images - warm gold like MonaLisa's hair
  { mime = "image/*", fg = "#e2b55f" },

  # Media - artistic purple
  { mime = "{audio,video}/*", fg = "#6d7a72" },

  # Archives - terracotta red
  { mime = "application/*zip", fg = "#c46f41" },
  { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#c46f41" },

  # Documents - sage green
  { mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#7a8471" },

  # Special files
  { name = "*", is = "orphan", bg = "#c46f41" },
  { name = "*", is = "exec", fg = "#8a7c4a" },

  # Fallback - dusty rose
  { name = "*/", fg = "#b08080" },
]
