customCommands:
  containers:
    - name: "Show IP address"
      command: |
        docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' {{.Container.ID}}
      attach: false
      serviceNames: []
